# Generated by Django 4.2.1 on 2023-05-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.CharField(default='Hi, I am using Blogger.', max_length=256),
        ),
    ]
